// docs/实践/with_vue/vue_launcher/src/App.vue
<script setup lang="ts">
import { ref, computed } from "vue";
import { scanComponents, type ComponentInfo } from "./componentLoader";

const components = ref<ComponentInfo[]>(scanComponents());
const selectedComponent = ref<ComponentInfo | null>(
  components.value.length > 0 ? components.value[0] : null,
);

const currentComponent = computed(() => selectedComponent.value?.component);

function selectComponent(component: ComponentInfo) {
  selectedComponent.value = component;
}
</script>

<template>
  <div class="app">
    <!-- 侧边栏 - 组件列表 -->
    <aside class="sidebar">
      <h2 class="sidebar-title">组件列表</h2>
      <ul class="component-list">
        <li
          v-for="component in components"
          :key="component.path"
          class="component-item"
          :class="{ active: selectedComponent?.path === component.path }"
          @click="selectComponent(component)"
        >
          {{ component.name }}
        </li>
      </ul>
      <p v-if="components.length === 0" class="no-components">暂无组件</p>
    </aside>

    <!-- 主区域 - 组件预览 -->
    <main class="main-content">
      <template v-if="selectedComponent">
        <div class="preview-header">
          <h1>{{ selectedComponent.name }}</h1>
          <span class="file-path">{{ selectedComponent.path }}</span>
        </div>
        <div class="preview-container">
          <component :is="currentComponent" />
        </div>
      </template>
      <div v-else class="empty-state">
        <p>请添加 .vue 组件文件到上级目录</p>
      </div>
    </main>
  </div>
</template>

<style scoped>
.app {
  display: flex;
  height: 100vh;
  width: 100%;
}
</style>

// docs/实践/with_react/react_launcher/src/App.tsx
import { useState } from "react";
import { scanComponents, ComponentInfo } from "./componentLoader";
import "./index.css";

function App() {
  const [components] = useState<ComponentInfo[]>(() => scanComponents());
  const [selectedComponent, setSelectedComponent] =
    useState<ComponentInfo | null>(
      components.length > 0 ? components[0] : null,
    );

  return (
    <div className="app">
      {/* 侧边栏 - 组件列表 */}
      <aside className="sidebar">
        <h2 className="sidebar-title">组件列表</h2>
        <ul className="component-list">
          {components.map((component) => (
            <li
              key={component.path}
              className={`component-item ${
                selectedComponent?.path === component.path ? "active" : ""
              }`}
              onClick={() => setSelectedComponent(component)}
            >
              {component.name}
            </li>
          ))}
        </ul>
        {components.length === 0 && <p className="no-components">暂无组件</p>}
      </aside>

      {/* 主区域 - 组件预览 */}
      <main className="main-content">
        {selectedComponent ? (
          <>
            <div className="preview-header">
              <h1>{selectedComponent.name}</h1>
              <span className="file-path">{selectedComponent.path}</span>
            </div>
            <div className="preview-container">
              <selectedComponent.Component />
            </div>
          </>
        ) : (
          <div className="empty-state">
            <p>请添加 .tsx 或 .jsx 组件文件到上级目录</p>
          </div>
        )}
      </main>
    </div>
  );
}

export default App;
